name: smalltalkCI

on: 
  push:
  pull_request:
  schedule:
    - cron: "15 2 3 * *" #run job on the 3rd day of every month on the 15th minute of the 2nd hour

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        smalltalk: [ GemStone64-3.6.1, GemStone64-3.5.6, GemStone64-3.4.5, GemStone64-3.3.9, GemStone64-3.2.17, GemStone64-3.1.0.6 ]
        experimental: [ false ]
    continue-on-error: ${{ matrix.experimental }}
    name: ${{ matrix.smalltalk }}
    steps:
      - uses: actions/checkout@v2
      - uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-image: ${{ matrix.smalltalk }}
      - name: Run tests
        run: smalltalkci -s ${{ matrix.smalltalk }}
        shell: bash
        timeout-minutes: 20
  status:
    runs-on: ubuntu-18.04
    name: Report Status
    uses: ravsamhq/notify-slack-action@v1
    if: always()
    needs:
      - build
    with:
      status: ${{ build.status }} # required
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_DALEHENRICH }} # required
