name: smalltalkCI

on: 
  push:
  pull_request:
  schedule:
    - cron: "45 15 * * *"

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        smalltalk: [ GemStone64-3.6.1, GemStone64-3.5.6, GemStone64-3.4.5, GemStone64-3.3.9, GemStone64-3.2.17, GemStone64-3.1.0.6 ]
        experimental: [ false ]
    continue-on-error: ${{ matrix.experimental }}
    name: ${{ matrix.smalltalk }}
    steps:
      - uses: actions/checkout@v2
      - uses: hpi-swa/setup-smalltalkCI@v1
        with:
          smalltalk-version: ${{ matrix.smalltalk }}
      - name: Run tests
        run: smalltalkci -s ${{ matrix.smalltalk }}
        shell: bash
        timeout-minutes: 20
      - uses: ravsamhq/notify-slack-action@v1
        if: always()
        with:
          status: ${{ job.status }} # required
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.DALEHENRICH_CHANNEL }} # required
